Taking care of the --Frag
DV8FromTheWorld/JDA-Player pull request #22
Opened 2016-11-04 23:28 UTC by Fabricio20

And possible fix for the weird/wrong music bug.

This changes the constructors of RemoteSource, RemoteStream and PlayList (#getPlaylist too) to one that requires the guild id (So a folder can be made on the system for the guild).

This should be rewritten to support calls later on.

2016-11-04 23:34 UTC, TheEpTic approved these changes
10/10 MERGE

2016-11-05 14:16 UTC, AvalancheYT commented on Core/src/main/java/net/dv8tion/jda/player/source/RemoteSource.java
> +        return new RemoteStream(ytdlLaunchArgs, ffmpegLaunchArgs, this.guildId);
I don't think it needs a ```this```, otherwise, everything looks good.

2016-11-05 15:26 UTC, Fabricio20 commented on Core/src/main/java/net/dv8tion/jda/player/source/RemoteSource.java
> +        return new RemoteStream(ytdlLaunchArgs, ffmpegLaunchArgs, this.guildId);
While using `this` is not needed (in this case) it's always good to specify which instance we are working with.

2016-11-05 16:28 UTC, MinnDevelopment requested changes

2016-11-05 16:28 UTC, MinnDevelopment commented on Core/src/main/java/net/dv8tion/jda/player/source/RemoteSource.java
> +                    "--no-warning",         //Fuck you Annoying JSON error
Change the comment here

2016-11-05 16:28 UTC, MinnDevelopment commented on D4J/src/main/java/net/dv8tion/d4j/player/Bot.java
> +                Playlist playlist = Playlist.getPlaylist(url, event.getMessage().getGuild().getID());
getId() not getID

2016-11-05 16:28 UTC, MinnDevelopment commented on D4J/src/main/java/net/dv8tion/d4j/player/Bot.java
> +                Playlist playlist = Playlist.getPlaylist(url, event.getMessage().getGuild().getID());
In addition, please make sure all of this compiles as well.

2016-11-05 16:28 UTC, MinnDevelopment commented on Core/src/main/java/net/dv8tion/jda/player/source/RemoteSource.java
> +                    "--no-warning",         //Fuck you Annoying JSON error
Does `--no-part` actually affect anything?

2016-11-06 01:45 UTC, Fabricio20 commented on Core/src/main/java/net/dv8tion/jda/player/source/RemoteSource.java
> +                    "--no-warning",         //Fuck you Annoying JSON error
Ish I would say, if not present the amount of --Frag files is 2x.

2016-11-06 01:52 UTC, Fabricio20 commented on D4J/src/main/java/net/dv8tion/d4j/player/Bot.java
> +                Playlist playlist = Playlist.getPlaylist(url, event.getMessage().getGuild().getID());
getID is correct according to [D4J](https://github.com/nerd/Discord4J/blob/7f940d2a476a67177973eb11d9da25d01bed6c13/src/main/java/sx/blah/discord/handle/obj/Message.java#L88-L90)

2016-11-06 12:43 UTC, MinnDevelopment commented on D4J/src/main/java/net/dv8tion/d4j/player/Bot.java
> +                Playlist playlist = Playlist.getPlaylist(url, event.getMessage().getGuild().getID());
My bad I mixed up D4J and JDA here.

2016-11-06 12:44 UTC, MinnDevelopment approved these changes

2016-11-14 02:06 UTC, merged